server.port=8083

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication_db
spring.datasource.username=postgres
spring.datasource.password=Shaikali@270

# JPA/ Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
