spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE1
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payments/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
