server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.userService.sliding-window-size=5
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=2

# Feign timeout configuration
spring.cloud.openfeign.client.config.User-Service1.connectTimeout=3000
spring.cloud.openfeign.client.config.User-Service1.readTimeout=3000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always
